vnma0/wafter

- routes/score.js
- util/result.js
- util/score/ACM.js
- util/score/OI.js
- util/scoreboard.js
- New Wafter API: `/score` - Get current scoreboard
- New score API: `allowScoreboard: <Boolean>`
> Add Scoreboard

- src/data/database.js
- src/util/userValid.js
- test/database_test.js
- Move `isPassword` outside
- Put `isUsername` and `isPassword` into userValid.js
- Seperate `updateUser` into `updateUserName` and `updateUserPassword` to get rid of complexity
> Database improvement

- src/routes/subs.js
- src/routes/users.js
- src/server.js
> Fix api route

- src/util/userValid.js
> Fix stupid error in code

- src/controller/initJudger.js
- src/controller/submitCode.js
- src/driver/kon.js
- test/kon_test.js
> Revised version of Kon

- src/routes/users.js
`PUT /api/user/:user_id` -> `PUT /api/user/:user_id/password`
> Move change password route

- src/controller/submitCode.js
Now there will be two reload requests:
- First one: Immediate
- Second: after 45s
> Cycle upgrade

- src/data/database.js
- src/routes/subs.js
> Fix incorrect `count` variable & incorrect username

- src/data/database.js
- src/routes/subs.js
- src/util/config/contestConfig.js
- Route: `GET /api/subs/:id/source`
- Allow reading source code of the submission
- Download file is `{sub_id}{ext}`
- Problem list and Ext list will be limited
> Add feature to read submission's source

- src/data/database.js
> Patch unhandled promise in readAllSubmissions

- src/data/database.js
> Completely handle all unhandled promise in db

- src/data/database.js
> resolve #72 once again

- package.json
- src/server.js
- resolve #76 
- Support hestia [v1.5.2-20190421.1](https://github.com/vnma0/hestia/releases/tag/v1.5.2-20190421.1)
> Use expressStaticGzip to serve instead

- src/config/version.js
- src/index.js
- Merge into `appveyor-rev` branch due to parallel implementaion
> Config versioning

- .gitignore
- .sample.env
- appveyor.yml
- package.json
- src/config/server.js
- src/index.js
- src/middleware/log.js
- src/routes/subs.js
- src/server.js
- src/util/config/serverConfig.js
- Rewrite app config to ~fully~ base on env vars.
- Seperate parser for app config
- ~add `DISABLE_BRUTE_PREVENT` option~ _removed due to unnecessary_
- resolve #64 
- resolve #68 
- resolve #69
> Rewrite app config

- appveyor.yml
- package.json
- src/config/version.js
- src/index.js
- Simplify building process and condition
- Bump version: v1.15.0
- New version system: `MAJOR.MINOR.PATCH` Build `NUMBER`
- Add version to build
- Add 2019 to copyright year
> Revamp appveyor.yml

- hestia.sh
Simply just add shell script to add download support for GNU/Linux and macOS
> Add shell script

- .github/workflows/main.yml
> Add GitHub Actions configuration

- .github/workflows/main.yml
- contest.sample.json
- kon.sample.json
- src/config/server.js
- src/controller/kon.js
- src/index.js
- src/middleware/bruteForce.js
- src/middleware/upload.js
- src/prompt/contestConfig/mode.js
- src/routes/subs.js
- src/routes/users.js
- src/server.js
- src/util/config/contestConfig.js
- src/util/parseKon.js
- ~Move verdict summerizing to Kon~ (Removed feature due to upcoming change)
> Increase security (and perhaps performance)

- src/controller/database.js
- Reason: Make communication and data transformation easier.
> fix: remove base64 encode of msg in database

- src/routes/users.js
> fix: Allow registeration without login credential
